// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsoxsaikapkflwkgcrlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzb3hzYWlrYXBrZmx3a2djcmxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzQ3MjYsImV4cCI6MjA2MjYxMDcyNn0.2h3pvk1u3wBVoWQGrsvLU360N-bI3qSxKTvhDsHxpPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);